version: '2'
services:
web:
build: .
restart: always

depends_on:
- db


command: python odoo-bin -c /etc/odoo.conf --xmlrpc-port 8069
links:
- db

db:
image: postgres:9.4
environment:
- POSTGRES_PASSWORD=odoo
- POSTGRES_USER=odoo
- PGDATA=/var/lib/postgresql/data/pgdata

ports:
- "5434:5434"

volumes:
  odoo-web-data:
  odoo-db-data: